version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: larisa_pdf
      POSTGRES_PASSWORD: hSdXvBKRhZO4eAjF7TatJ9R
      POSTGRES_DB: pdf_database_upwork
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U larisa_pdf"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: app_backend
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/backend  # исключаем папку backend из монтирования (опционально)
    working_dir: /app/backend

volumes:
  postgres_data:
